# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    # NODE NPM YARN #
    - uses: actions/checkout@v3
    - name: Install Node.js 16.16.0 v16.16.0 npm 8.11.0 yarn 1.22.19
      uses: actions/setup-node@v3
      with:
        node-version: "16.16.0"
        
    # GO #
    - uses: actions/checkout@v3
    - name: Install Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    # ??? #
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Java version
      run: |
        echo java version
        java -version
        mvn -v 
        gradle -v
        
        
    # PYTHON #
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
#        python -m pip install --upgrade pip

    # RUN TESTS #
    - name: Test with pytest
      run: |
        pytest
